# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MenuNombreApellido.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QLineEdit,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QWidget)

class Ui_vtnPrincipal(object):
    def setupUi(self, vtnPrincipal):
        if not vtnPrincipal.objectName():
            vtnPrincipal.setObjectName(u"vtnPrincipal")
        vtnPrincipal.resize(657, 491)
        font = QFont()
        font.setPointSize(10)
        vtnPrincipal.setFont(font)
        self.centralwidget = QWidget(vtnPrincipal)
        self.centralwidget.setObjectName(u"centralwidget")
        self.lblNombre = QLabel(self.centralwidget)
        self.lblNombre.setObjectName(u"lblNombre")
        self.lblNombre.setGeometry(QRect(60, 80, 69, 22))
        font1 = QFont()
        font1.setFamilies([u"Times New Roman"])
        font1.setPointSize(14)
        font1.setBold(True)
        font1.setItalic(True)
        self.lblNombre.setFont(font1)
        self.lblApellido = QLabel(self.centralwidget)
        self.lblApellido.setObjectName(u"lblApellido")
        self.lblApellido.setGeometry(QRect(60, 130, 74, 22))
        self.lblApellido.setFont(font1)
        self.txtNombre = QLineEdit(self.centralwidget)
        self.txtNombre.setObjectName(u"txtNombre")
        self.txtNombre.setGeometry(QRect(150, 80, 291, 21))
        self.txtNombre.setMaxLength(20)
        self.txtApellido = QLineEdit(self.centralwidget)
        self.txtApellido.setObjectName(u"txtApellido")
        self.txtApellido.setGeometry(QRect(150, 130, 291, 21))
        self.txtApellido.setFont(font)
        self.txtApellido.setMaxLength(20)
        self.btnGuardar = QPushButton(self.centralwidget)
        self.btnGuardar.setObjectName(u"btnGuardar")
        self.btnGuardar.setGeometry(QRect(520, 390, 101, 41))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        font2.setUnderline(True)
        self.btnGuardar.setFont(font2)
        self.txtCedula = QLineEdit(self.centralwidget)
        self.txtCedula.setObjectName(u"txtCedula")
        self.txtCedula.setGeometry(QRect(150, 180, 151, 21))
        self.txtCedula.setFont(font)
        self.txtCedula.setMaxLength(10)
        self.lblApellido_2 = QLabel(self.centralwidget)
        self.lblApellido_2.setObjectName(u"lblApellido_2")
        self.lblApellido_2.setGeometry(QRect(60, 180, 74, 22))
        self.lblApellido_2.setFont(font1)
        self.btnLimpiar = QPushButton(self.centralwidget)
        self.btnLimpiar.setObjectName(u"btnLimpiar")
        self.btnLimpiar.setGeometry(QRect(30, 390, 101, 41))
        self.btnLimpiar.setFont(font2)
        self.cbSexo = QComboBox(self.centralwidget)
        self.cbSexo.addItem("")
        self.cbSexo.addItem("")
        self.cbSexo.addItem("")
        self.cbSexo.addItem("")
        self.cbSexo.setObjectName(u"cbSexo")
        self.cbSexo.setGeometry(QRect(150, 280, 181, 21))
        self.lblSexo = QLabel(self.centralwidget)
        self.lblSexo.setObjectName(u"lblSexo")
        self.lblSexo.setGeometry(QRect(60, 280, 74, 22))
        self.lblSexo.setFont(font1)
        self.txtCedula_Buscar = QLineEdit(self.centralwidget)
        self.txtCedula_Buscar.setObjectName(u"txtCedula_Buscar")
        self.txtCedula_Buscar.setGeometry(QRect(210, 40, 181, 21))
        self.txtCedula_Buscar.setFont(font)
        self.txtCedula_Buscar.setMaxLength(10)
        self.lblBuscarPorCedula = QLabel(self.centralwidget)
        self.lblBuscarPorCedula.setObjectName(u"lblBuscarPorCedula")
        self.lblBuscarPorCedula.setGeometry(QRect(60, 30, 131, 31))
        self.lblBuscarPorCedula.setFont(font1)
        self.btnBuscar = QPushButton(self.centralwidget)
        self.btnBuscar.setObjectName(u"btnBuscar")
        self.btnBuscar.setGeometry(QRect(460, 30, 91, 31))
        self.btnBuscar.setFont(font2)
        self.txtEmail = QLineEdit(self.centralwidget)
        self.txtEmail.setObjectName(u"txtEmail")
        self.txtEmail.setGeometry(QRect(150, 230, 381, 21))
        self.txtEmail.setFont(font)
        self.txtEmail.setMaxLength(40)
        self.lblApellido_3 = QLabel(self.centralwidget)
        self.lblApellido_3.setObjectName(u"lblApellido_3")
        self.lblApellido_3.setGeometry(QRect(60, 230, 74, 22))
        self.lblApellido_3.setFont(font1)
        self.cbEstado = QComboBox(self.centralwidget)
        self.cbEstado.addItem("")
        self.cbEstado.addItem("")
        self.cbEstado.addItem("")
        self.cbEstado.addItem("")
        self.cbEstado.setObjectName(u"cbEstado")
        self.cbEstado.setGeometry(QRect(190, 330, 181, 21))
        self.lblEstado = QLabel(self.centralwidget)
        self.lblEstado.setObjectName(u"lblEstado")
        self.lblEstado.setGeometry(QRect(60, 330, 121, 22))
        self.lblEstado.setFont(font1)
        self.btnEliminar = QPushButton(self.centralwidget)
        self.btnEliminar.setObjectName(u"btnEliminar")
        self.btnEliminar.setGeometry(QRect(410, 390, 101, 41))
        self.btnEliminar.setFont(font2)
        self.btnActualizar = QPushButton(self.centralwidget)
        self.btnActualizar.setObjectName(u"btnActualizar")
        self.btnActualizar.setGeometry(QRect(300, 390, 101, 41))
        self.btnActualizar.setFont(font2)
        vtnPrincipal.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(vtnPrincipal)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 657, 21))
        vtnPrincipal.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(vtnPrincipal)
        self.statusbar.setObjectName(u"statusbar")
        vtnPrincipal.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.txtNombre, self.txtApellido)
        QWidget.setTabOrder(self.txtApellido, self.txtCedula)
        QWidget.setTabOrder(self.txtCedula, self.btnGuardar)

        self.retranslateUi(vtnPrincipal)

        QMetaObject.connectSlotsByName(vtnPrincipal)
    # setupUi

    def retranslateUi(self, vtnPrincipal):
        vtnPrincipal.setWindowTitle(QCoreApplication.translate("vtnPrincipal", u"Servicio Personas", None))
        self.lblNombre.setText(QCoreApplication.translate("vtnPrincipal", u"Nombre:", None))
        self.lblApellido.setText(QCoreApplication.translate("vtnPrincipal", u"Apellido:", None))
        self.btnGuardar.setText(QCoreApplication.translate("vtnPrincipal", u"Guardar", None))
        self.lblApellido_2.setText(QCoreApplication.translate("vtnPrincipal", u"Cedula:", None))
        self.btnLimpiar.setText(QCoreApplication.translate("vtnPrincipal", u"Limpiar", None))
        self.cbSexo.setItemText(0, QCoreApplication.translate("vtnPrincipal", u"Seleccione...", None))
        self.cbSexo.setItemText(1, QCoreApplication.translate("vtnPrincipal", u"Masculino", None))
        self.cbSexo.setItemText(2, QCoreApplication.translate("vtnPrincipal", u"Femenino", None))
        self.cbSexo.setItemText(3, QCoreApplication.translate("vtnPrincipal", u"Prefiero no decirlo", None))

        self.lblSexo.setText(QCoreApplication.translate("vtnPrincipal", u"Sexo:", None))
        self.lblBuscarPorCedula.setText(QCoreApplication.translate("vtnPrincipal", u"Buscar x cedula:", None))
        self.btnBuscar.setText(QCoreApplication.translate("vtnPrincipal", u"BUSCAR", None))
        self.lblApellido_3.setText(QCoreApplication.translate("vtnPrincipal", u"Email:", None))
        self.cbEstado.setItemText(0, QCoreApplication.translate("vtnPrincipal", u"Seleccione...", None))
        self.cbEstado.setItemText(1, QCoreApplication.translate("vtnPrincipal", u"Soltero", None))
        self.cbEstado.setItemText(2, QCoreApplication.translate("vtnPrincipal", u"Casado", None))
        self.cbEstado.setItemText(3, QCoreApplication.translate("vtnPrincipal", u"Divorciado", None))

        self.lblEstado.setText(QCoreApplication.translate("vtnPrincipal", u"Estado civil:", None))
        self.btnEliminar.setText(QCoreApplication.translate("vtnPrincipal", u"Eliminar", None))
        self.btnActualizar.setText(QCoreApplication.translate("vtnPrincipal", u"Actualizar", None))
    # retranslateUi

